import localFont from "next/font/local";
import "./globals.css";
 import Navbar from "@/app/components/header/navbar";
import PageTransition from "@/app/components/header/pagetransition";
import StairTransition from "@/app/components/header/stairtransition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Reeha Batool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar/>
      <StairTransition/>
      <PageTransition >

          {children}
      </PageTransition>

      </body>
    </html>
  );
}
